
version: '3'
services:
  product-service:
    container_name: product-service
    build:  .
    depends_on:
      - mysql
    ports:
      - 8084:8084

  mysql:
    container_name: mysqldb
    image: mysql:8.0.33
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: products


